name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: mskelton/setup-yarn@v1
        with:
          version: latest

      - name: Install Node.js dependencies
        run: yarn install

      - name: Build TypeScript and bundle into asar
        run: yarn run bundle

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bundle/*"
          makeLatest: true
